version: "3.3"

services:
  cluster-rewarding: # name of the service
    build: .
    image: cluster-rewarding # the image to use
    container_name: cluster-rewarding # what to label the container for docker ps
    restart: always # restart if failed, until we stop it ourselves
    depends_on:
      - ipfs-cluster-client
    networks:
      - cluster-rewarding-client
    env_file:
      - .env
    command:
      - npm
      - run 
      - start:client
    environment:
      IPFS_HOST: ipfs-cluster-client:5001

  ipfs-cluster:
    container_name: 3speak-cluster
    image: ipfs/ipfs-cluster:1.0.6
    entrypoint:
      - /usr/local/bin/ipfs-cluster-follow
      - 3speak-cluster 
      - run 
      - --init https://ipfs.3speak.tv/ipns/ipfs-cluster.3speak.tv
    networks:
      - cluster-rewarding-client
  ipfs-cluster-client:
    container_name: ipfs-instance
    image: ipfs/kubo:v0.19.0
    command:
      - daemon
      - --enable-pubsub-experiment
    networks:
      - cluster-rewarding-client

networks:
  cluster-rewarding-client:
    driver: bridge
