version: "3.3"

services:
  # cluster-rewarding: # name of the service
  #   build: .
  #   image: cluster-rewarding # the image to use
  #   container_name: cluster-rewarding # what to label the container for docker ps
  #   restart: always # restart if failed, until we stop it ourselves
  #   depends_on:
  #     - ipfs
  #   networks:
  #     - cluster-rewarding-client
  #   environment:
  #     IPFS_HOST: ipfs:5001

  ipfs-cluster:
    container_name: 3speak-cluster
    image: ipfs/ipfs-cluster:1.0.6
    entrypoint:
      - /usr/local/bin/ipfs-cluster-follow
      - 3speak-cluster 
      - run 
      - --init ipfs-cluster.3speak.tv
    networks:
      - cluster-rewarding-client
  ipfs:
    container_name: ipfs-cluster
    image: ipfs/kubo:v0.19.0
    command:
      - daemon
      - --enable-pubsub-experiment
    networks:
      - cluster-rewarding-client

networks:
  cluster-rewarding-client:
    driver: bridge
