version: "3.3"

services:
  cluster-rewarding: # name of the service
    build: .
    image: cluster-rewarding # the image to use
    container_name: cluster-rewarding # what to label the container for docker ps
    restart: always # restart if failed, until we stop it ourselves
    depends_on:
      - ipfs
    networks:
      - cluster-rewarding-server
    env_file:
      - .env
    environment:
      IPFS_HOST: ipfs:5001
  ipfs:
    container_name: ipfs-cluster
    image: ipfs/kubo:v0.19.0
    command:
      - daemon
      - --enable-pubsub-experiment
    networks:
      - cluster-rewarding-server

networks:
  cluster-rewarding-server:
    driver: bridge
