version: "3.3"

services:
  cluster-rewarding: # name of the service
    build: .
    image: cluster-rewarding # the image to use
    container_name: cluster-rewarding # what to label the container for docker ps
    restart: always # restart if failed, until we stop it ourselves
    depends_on:
      - ipfs-cluster-client
    networks:
      - cluster-rewarding-client
    env_file:
      - .env
    command:
      - npm
      - run 
      - start:client
    environment:
      IPFS_HOST: http://ipfs-cluster-client:5001

  ipfs-cluster:
    container_name: cluster-rewarding-follower
    image: ipfs/ipfs-cluster:1.0.6
    restart: always
    entrypoint:
      - /usr/local/bin/ipfs-cluster-follow
      - 3speak-cluster 
      - run 
      - --init 
      - https://ipfs.3speak.tv/ipns/ipfs-cluster.3speak.tv
    environment:
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs-cluster-client/tcp/5001
    networks:
      - cluster-rewarding-client
    volumes:
      - ./data/ipfs-cluster:/data/ipfs-cluster
  ipfs-cluster-client:
    container_name: cluster-rewarding-ipfs
    image: ipfs/kubo:v0.19.0
    restart: always
    command:
      - daemon
      - --enable-pubsub-experiment
    environment: 
      IPFS_PATH: /etc/ipfs
    volumes:
      - ./data/ipfs:/etc/ipfs
    ports: 
      - 4001:4001
      - 5011:5001
    networks:
      - cluster-rewarding-client

networks:
  cluster-rewarding-client:
    driver: bridge
